"""
Prompt templates for sub-agents.

Each sub-agent type has specialized system and task prompts optimized
for its domain: coding, research, review, or architecture.
"""

from .coder_prompts import CODER_SYSTEM_PROMPT, CODER_TASK_PROMPT
from .research_prompts import RESEARCH_SYSTEM_PROMPT, RESEARCH_TASK_PROMPT
from .review_prompts import REVIEW_SYSTEM_PROMPT, REVIEW_TASK_PROMPT
from .architect_prompts import (
    ARCHITECT_SYSTEM_PROMPT,
    ARCHITECT_TASK_PROMPT,
    ARCHITECT_PHASE1_DISCOVERY,
    ARCHITECT_PHASE2_ANALYSIS,
    ARCHITECT_PHASE3_DESIGN,
    ARCHITECT_PHASE4_CRITIQUE,
    ARCHITECT_PHASE5_REFINEMENT,
    ARCHITECT_PHASE6_SYNTHESIS,
)

__all__ = [
    "CODER_SYSTEM_PROMPT",
    "CODER_TASK_PROMPT",
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_TASK_PROMPT",
    "REVIEW_SYSTEM_PROMPT",
    "REVIEW_TASK_PROMPT",
    "ARCHITECT_SYSTEM_PROMPT",
    "ARCHITECT_TASK_PROMPT",
    "ARCHITECT_PHASE1_DISCOVERY",
    "ARCHITECT_PHASE2_ANALYSIS",
    "ARCHITECT_PHASE3_DESIGN",
    "ARCHITECT_PHASE4_CRITIQUE",
    "ARCHITECT_PHASE5_REFINEMENT",
    "ARCHITECT_PHASE6_SYNTHESIS",
]