import { PROVIDER_DEFAULTS, PROVIDER_IDS, type Language, type ProviderDefinition, type ProviderId } from './types.js';

export const PROVIDER_DEFINITIONS: Record<ProviderId, ProviderDefinition> = {
  openai: {
    id: 'openai',
    label: 'OpenAI',
    description: 'Hosted OpenAI models with a simple chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.openai.baseUrl,
    defaultModel: PROVIDER_DEFAULTS.openai.model,
    requiresApiKey: true,
    staticModels: ['gpt-6.1-sol', 'gpt-4o-mini', 'gpt-4o', 'gpt-4.1-mini', 'o4-mini'],
  },
  anthropic: {
    id: 'anthropic',
    label: 'Anthropic',
    description: 'Claude models through the Anthropic Messages API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.anthropic.baseUrl,
    requiresApiKey: true,
    staticModels: ['claude-3-5-sonnet-latest', 'claude-3-5-haiku-latest', 'claude-3-opus-latest'],
  },
  gemini: {
    id: 'gemini',
    label: 'Google Gemini',
    description: 'Google generative models with a native API shape.',
    defaultBaseUrl: PROVIDER_DEFAULTS.gemini.baseUrl,
    requiresApiKey: true,
    staticModels: ['gemini-2.0-flash', 'gemini-2.0-flash-lite', 'gemini-1.5-pro'],
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    description: 'A single interface to many hosted model providers.',
    defaultBaseUrl: PROVIDER_DEFAULTS.openrouter.baseUrl,
    requiresApiKey: true,
    staticModels: ['openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet', 'google/gemini-2.0-flash-001'],
  },
  deepseek: {
    id: 'deepseek',
    label: 'DeepSeek',
    description: 'DeepSeek chat and reasoning models, billed cheaply per token.',
    defaultBaseUrl: PROVIDER_DEFAULTS.deepseek.baseUrl,
    requiresApiKey: true,
    staticModels: ['deepseek-chat', 'deepseek-reasoner'],
  },
  mistral: {
    id: 'mistral',
    label: 'Mistral',
    description: 'Mistral’s hosted open and code models over a chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.mistral.baseUrl,
    requiresApiKey: true,
    staticModels: ['mistral-small-latest', 'mistral-large-latest', 'codestral-latest', 'open-mistral-nemo'],
  },
  groq: {
    id: 'groq',
    label: 'Groq',
    description: 'Very fast hosted inference on open-weight models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.groq.baseUrl,
    requiresApiKey: true,
    staticModels: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'open-mixtral-8x7b-32768', 'gemma2-9b-it'],
  },
  xai: {
    id: 'xai',
    label: 'xAI',
    description: 'Grok models from xAI through an OpenAI-compatible API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.xai.baseUrl,
    requiresApiKey: true,
    staticModels: ['grok-2-latest', 'grok-2-mini', 'grok-beta'],
  },
  ollama: {
    id: 'ollama',
    label: 'Local / Ollama',
    description: 'A private endpoint on your machine or LAN.',
    defaultBaseUrl: PROVIDER_DEFAULTS.ollama.baseUrl,
    requiresApiKey: false,
    staticModels: ['llama3.2', 'llama3.1', 'mistral', 'qwen2.5'],
  },
  lmstudio: {
    id: 'lmstudio',
    label: 'Local / LM Studio',
    description: 'A local LM Studio server on your machine, with no key required.',
    defaultBaseUrl: PROVIDER_DEFAULTS.lmstudio.baseUrl,
    requiresApiKey: false,
    staticModels: ['qwen2.5-7b-instruct', 'llama-3.2-3b-instruct', 'gemma-2-2b-it'],
  },
  together: {
    id: 'together',
    label: 'Together AI',
    description: 'Hosted open-weight models through an OpenAI-compatible API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.together.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct-Turbo', 'Qwen/Qwen2.5-72B-Instruct-Turbo', 'deepseek-ai/DeepSeek-V3'],
  },
  fireworks: {
    id: 'fireworks',
    label: 'Fireworks AI',
    description: 'Fast hosted inference on open and fine-tuned models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.fireworks.baseUrl,
    requiresApiKey: true,
    staticModels: ['accounts/fireworks/models/llama4-maverick-instruct-basic', 'accounts/fireworks/models/deepseek-v3'],
  },
  deepinfra: {
    id: 'deepinfra',
    label: 'DeepInfra',
    description: 'Cheaply billed hosted inference on open-weight models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.deepinfra.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct', 'deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct'],
  },
  cerebras: {
    id: 'cerebras',
    label: 'Cerebras',
    description: 'Extremely fast hosted inference on open-weight models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.cerebras.baseUrl,
    requiresApiKey: true,
    staticModels: ['llama-3.3-70b', 'llama3.1-8b', 'qwen-3-32b'],
  },
  sambanova: {
    id: 'sambanova',
    label: 'SambaNova Cloud',
    description: 'Hosted inference on open-weight models at high throughput.',
    defaultBaseUrl: PROVIDER_DEFAULTS.sambanova.baseUrl,
    requiresApiKey: true,
    staticModels: ['Meta-Llama-3.3-70B-Instruct', 'Qwen2.5-72B-Instruct'],
  },
  cohere: {
    id: 'cohere',
    label: 'Cohere',
    description: 'Command models through an OpenAI-compatible endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.cohere.baseUrl,
    requiresApiKey: true,
    staticModels: ['command-a-03-2025', 'command-r-plus-08-2024', 'command-r-08-2024'],
  },
  perplexity: {
    id: 'perplexity',
    label: 'Perplexity',
    description: 'Search-grounded Sonar models with citations.',
    defaultBaseUrl: PROVIDER_DEFAULTS.perplexity.baseUrl,
    requiresApiKey: true,
    staticModels: ['sonar', 'sonar-pro', 'sonar-reasoning'],
  },
  bedrock: {
    id: 'bedrock',
    label: 'AWS Bedrock',
    description: 'AWS-hosted models; point the endpoint at your region and key at AWS.',
    defaultBaseUrl: PROVIDER_DEFAULTS.bedrock.baseUrl,
    requiresApiKey: true,
    staticModels: ['anthropic.claude-3-5-sonnet-20241022-v2:0', 'amazon.nova-pro-v1:0', 'meta.llama3-3-70b-instruct-v1:0'],
  },
  azure: {
    id: 'azure',
    label: 'Microsoft Azure AI',
    description: 'Azure-hosted models; the endpoint names your resource.',
    defaultBaseUrl: PROVIDER_DEFAULTS.azure.baseUrl,
    requiresApiKey: true,
    staticModels: ['gpt-4o-mini', 'gpt-4o', 'o4-mini'],
  },
  vertex: {
    id: 'vertex',
    label: 'Google Vertex AI',
    description: 'Vertex-hosted models; the endpoint names your project and region.',
    defaultBaseUrl: PROVIDER_DEFAULTS.vertex.baseUrl,
    requiresApiKey: true,
    staticModels: ['gemini-2.0-flash', 'gemini-2.5-pro'],
  },
  huggingface: {
    id: 'huggingface',
    label: 'Hugging Face Inference API',
    description: 'Hosted inference across the Hub through one router.',
    defaultBaseUrl: PROVIDER_DEFAULTS.huggingface.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen2.5-72B-Instruct'],
  },
  replicate: {
    id: 'replicate',
    label: 'Replicate',
    description: 'Hosted models and fine-tunes billed by the second.',
    defaultBaseUrl: PROVIDER_DEFAULTS.replicate.baseUrl,
    requiresApiKey: true,
    staticModels: ['openai/gpt-4o-mini', 'meta/meta-llama-3.1-405b-instruct'],
  },
  cloudflare: {
    id: 'cloudflare',
    label: 'Cloudflare Workers AI',
    description: 'Edge-hosted models; the endpoint names your account.',
    defaultBaseUrl: PROVIDER_DEFAULTS.cloudflare.baseUrl,
    requiresApiKey: true,
    staticModels: ['@cf/meta/llama-3.3-70b-instruct-fp8-fast', '@cf/qwen/qwen2.5-coder-32b-instruct'],
  },
  nvidia: {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    description: 'NVIDIA-hosted inference microservices for open models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.nvidia.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta/llama-3.3-70b-instruct', 'nvidia/llama-3.1-nemotron-70b-instruct'],
  },
  siliconflow: {
    id: 'siliconflow',
    label: 'SiliconFlow',
    description: 'Hosted Chinese and open-weight models at scale.',
    defaultBaseUrl: PROVIDER_DEFAULTS.siliconflow.baseUrl,
    requiresApiKey: true,
    staticModels: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct'],
  },
  nebius: {
    id: 'nebius',
    label: 'Nebius AI',
    description: 'Hosted open-weight models on Nebius AI Studio.',
    defaultBaseUrl: PROVIDER_DEFAULTS.nebius.baseUrl,
    requiresApiKey: true,
    staticModels: ['deepseek-ai/DeepSeek-V3', 'meta-llama/Llama-3.3-70B-Instruct'],
  },
  baseten: {
    id: 'baseten',
    label: 'Baseten',
    description: 'Hosted and dedicated model deployments with a chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.baseten.baseUrl,
    requiresApiKey: true,
    staticModels: ['deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-4-Maverick-17B-128E-Instruct'],
  },
  zhipu: {
    id: 'zhipu',
    label: 'Zhipu AI',
    description: 'GLM models through an OpenAI-compatible endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.zhipu.baseUrl,
    requiresApiKey: true,
    staticModels: ['glm-4.5', 'glm-4-plus', 'glm-4-flash'],
  },
  dashscope: {
    id: 'dashscope',
    label: 'Alibaba Cloud / DashScope',
    description: 'Qwen models through the compatible-mode endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.dashscope.baseUrl,
    requiresApiKey: true,
    staticModels: ['qwen-max', 'qwen-plus', 'qwen-turbo'],
  },
  moonshot: {
    id: 'moonshot',
    label: 'Moonshot AI',
    description: 'Kimi models through an OpenAI-compatible endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.moonshot.baseUrl,
    requiresApiKey: true,
    staticModels: ['kimi-k2-0711-preview', 'moonshot-v1-8k', 'moonshot-v1-32k'],
  },
  minimax: {
    id: 'minimax',
    label: 'MiniMax',
    description: 'MiniMax text models through a chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.minimax.baseUrl,
    requiresApiKey: true,
    staticModels: ['MiniMax-Text-01', 'abab6.5s-chat'],
  },
  lambda: {
    id: 'lambda',
    label: 'Lambda Labs',
    description: 'Hosted inference on Lambda’s GPU cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.lambda.baseUrl,
    requiresApiKey: true,
    staticModels: ['llama3.3-70b-instruct', 'hermes3-70b'],
  },
  runpod: {
    id: 'runpod',
    label: 'RunPod',
    description: 'Serverless endpoints on RunPod’s GPU cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.runpod.baseUrl,
    requiresApiKey: true,
    staticModels: ['openai/gpt-oss-120b', 'deepseek-ai/DeepSeek-V3'],
  },
  vastai: {
    id: 'vastai',
    label: 'Vast.ai',
    description: 'Bargain GPU cloud with an OpenAI-compatible proxy.',
    defaultBaseUrl: PROVIDER_DEFAULTS.vastai.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  coreweave: {
    id: 'coreweave',
    label: 'CoreWeave',
    description: 'AI-cloud hosted inference on CoreWeave.',
    defaultBaseUrl: PROVIDER_DEFAULTS.coreweave.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  modal: {
    id: 'modal',
    label: 'Modal',
    description: 'Web endpoints served from Modal functions.',
    defaultBaseUrl: PROVIDER_DEFAULTS.modal.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  anyscale: {
    id: 'anyscale',
    label: 'Anyscale',
    description: 'Hosted endpoints on Anyscale’s ray cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.anyscale.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3-70b-instruct'],
  },
  octoai: {
    id: 'octoai',
    label: 'OctoAI',
    description: 'Hosted text and image endpoints on OctoAI.',
    defaultBaseUrl: PROVIDER_DEFAULTS.octoai.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama-3.1-8b-instruct'],
  },
  lepton: {
    id: 'lepton',
    label: 'Lepton AI',
    description: 'Hosted models and deployments on Lepton.',
    defaultBaseUrl: PROVIDER_DEFAULTS.lepton.baseUrl,
    requiresApiKey: true,
    staticModels: ['llama3.3-70b'],
  },
  fluidstack: {
    id: 'fluidstack',
    label: 'FluidStack',
    description: 'GPU cloud inference on FluidStack.',
    defaultBaseUrl: PROVIDER_DEFAULTS.fluidstack.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  jarvislabs: {
    id: 'jarvislabs',
    label: 'Jarvis Labs',
    description: 'GPU cloud inference on Jarvis Labs.',
    defaultBaseUrl: PROVIDER_DEFAULTS.jarvislabs.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  paperspace: {
    id: 'paperspace',
    label: 'Paperspace / DigitalOcean',
    description: 'Hosted inference on Paperspace by DigitalOcean.',
    defaultBaseUrl: PROVIDER_DEFAULTS.paperspace.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  watsonx: {
    id: 'watsonx',
    label: 'IBM Watsonx',
    description: 'Watsonx-hosted models; the endpoint names your region.',
    defaultBaseUrl: PROVIDER_DEFAULTS.watsonx.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/llama-3-3-70b-instruct', 'ibm/granite-3-8b-instruct'],
  },
  oci: {
    id: 'oci',
    label: 'Oracle Cloud Infrastructure AI',
    description: 'OCI Generative AI; the endpoint names your region.',
    defaultBaseUrl: PROVIDER_DEFAULTS.oci.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta.llama-3.3-70b-instruct'],
  },
  qianfan: {
    id: 'qianfan',
    label: 'Baidu Wenxin / Qianfan',
    description: 'ERNIE models through the Qianfan v2 endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.qianfan.baseUrl,
    requiresApiKey: true,
    staticModels: ['ernie-4.5-turbo-128k', 'ernie-speed-128k'],
  },
  tencent: {
    id: 'tencent',
    label: 'Tencent Cloud TI Platform',
    description: 'Hunyuan models through the TI Platform endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.tencent.baseUrl,
    requiresApiKey: true,
    staticModels: ['hunyuan-turbos-latest', 'hunyuan-large'],
  },
  pangu: {
    id: 'pangu',
    label: 'Huawei Cloud Pangu',
    description: 'Pangu and hosted models on Huawei Cloud MaaS.',
    defaultBaseUrl: PROVIDER_DEFAULTS.pangu.baseUrl,
    requiresApiKey: true,
    staticModels: ['DeepSeek-R1', 'pangu-nlp'],
  },
  volcengine: {
    id: 'volcengine',
    label: 'ByteDance / Volcano Engine',
    description: 'Doubao models through the Ark v3 endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.volcengine.baseUrl,
    requiresApiKey: true,
    staticModels: ['doubao-pro-32k', 'doubao-1.5-pro-32k'],
  },
  sensenova: {
    id: 'sensenova',
    label: 'SenseTime / SenseNova',
    description: 'SenseChat models through the compatible-mode endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.sensenova.baseUrl,
    requiresApiKey: true,
    staticModels: ['SenseChat-5'],
  },
  ai21: {
    id: 'ai21',
    label: 'AI21 Labs',
    description: 'Jamba models through the AI21 studio API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.ai21.baseUrl,
    requiresApiKey: true,
    staticModels: ['jamba-large-1.7', 'jamba-mini-1.7'],
  },
  alephalpha: {
    id: 'alephalpha',
    label: 'Aleph Alpha',
    description: 'European models through the Aleph Alpha API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.alephalpha.baseUrl,
    requiresApiKey: true,
    staticModels: ['pharia-1-7b-control'],
  },
  sakana: {
    id: 'sakana',
    label: 'Sakana AI',
    description: 'Sakana AI models through an OpenAI-compatible endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.sakana.baseUrl,
    requiresApiKey: true,
    staticModels: ['sakana-model'],
  },
  reka: {
    id: 'reka',
    label: 'Reka AI',
    description: 'Reka multimodal models through a chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.reka.baseUrl,
    requiresApiKey: true,
    staticModels: ['reka-core', 'reka-flash', 'reka-edge'],
  },
  lighton: {
    id: 'lighton',
    label: 'LightOn',
    description: 'Hosted French and European models by LightOn.',
    defaultBaseUrl: PROVIDER_DEFAULTS.lighton.baseUrl,
    requiresApiKey: true,
    staticModels: ['lighton-model'],
  },
  upstage: {
    id: 'upstage',
    label: 'Upstage',
    description: 'Solar models through the Upstage API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.upstage.baseUrl,
    requiresApiKey: true,
    staticModels: ['solar-pro', 'solar-mini'],
  },
  novita: {
    id: 'novita',
    label: 'Novita AI',
    description: 'Cheap hosted inference on many open-weight models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.novita.baseUrl,
    requiresApiKey: true,
    staticModels: ['deepseek/deepseek-v3', 'meta-llama/llama-3.3-70b-instruct'],
  },
  monsterapi: {
    id: 'monsterapi',
    label: 'MonsterAPI',
    description: 'Hosted deployments through the MonsterAPI.',
    defaultBaseUrl: PROVIDER_DEFAULTS.monsterapi.baseUrl,
    requiresApiKey: true,
    staticModels: ['monster-model'],
  },
  predibase: {
    id: 'predibase',
    label: 'Predibase',
    description: 'Fine-tuned and open models served by Predibase.',
    defaultBaseUrl: PROVIDER_DEFAULTS.predibase.baseUrl,
    requiresApiKey: true,
    staticModels: ['llama-3-8b-instruct'],
  },
  hyperbolic: {
    id: 'hyperbolic',
    label: 'Hyperbolic Labs',
    description: 'Low-cost hosted inference on open-weight models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.hyperbolic.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct', 'deepseek-ai/DeepSeek-V3'],
  },
  akash: {
    id: 'akash',
    label: 'Akash Network',
    description: 'Decentralised GPU network with an OpenAI-compatible chat API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.akash.baseUrl,
    requiresApiKey: true,
    staticModels: ['Meta-Llama-3-1-8B-Instruct-FP8'],
  },
  crusoe: {
    id: 'crusoe',
    label: 'Crusoe Energy',
    description: 'Climate-aligned GPU cloud inference on Crusoe.',
    defaultBaseUrl: PROVIDER_DEFAULTS.crusoe.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  rendernetwork: {
    id: 'rendernetwork',
    label: 'Render Network',
    description: 'Decentralised GPU network APIs on Render.',
    defaultBaseUrl: PROVIDER_DEFAULTS.rendernetwork.baseUrl,
    requiresApiKey: true,
    staticModels: ['render-model'],
  },
  linode: {
    id: 'linode',
    label: 'Linode AI / Akamai',
    description: 'Hosted inference on Akamai’s Linode cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.linode.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  vultr: {
    id: 'vultr',
    label: 'Vultr Cloud GPU',
    description: 'Hosted inference on Vultr’s cloud GPU fleet.',
    defaultBaseUrl: PROVIDER_DEFAULTS.vultr.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama-3-8b-instruct'],
  },
  scaleway: {
    id: 'scaleway',
    label: 'Scaleway AI',
    description: 'European hosted inference on Scaleway.',
    defaultBaseUrl: PROVIDER_DEFAULTS.scaleway.baseUrl,
    requiresApiKey: true,
    staticModels: ['qwen2.5-72b-instruct', 'llama-3.1-8b-instruct'],
  },
  ovhcloud: {
    id: 'ovhcloud',
    label: 'OVHcloud AI',
    description: 'European hosted inference on OVHcloud Endpoints.',
    defaultBaseUrl: PROVIDER_DEFAULTS.ovhcloud.baseUrl,
    requiresApiKey: true,
    staticModels: ['Llama-3.3-70B-Instruct', 'Qwen2.5-72B-Instruct'],
  },
  hetzner: {
    id: 'hetzner',
    label: 'Hetzner Cloud GPU',
    description: 'Dedicated GPU servers on Hetzner Cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.hetzner.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  genesis: {
    id: 'genesis',
    label: 'Genesis Cloud',
    description: 'GPU cloud inference on Genesis Cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.genesis.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  civo: {
    id: 'civo',
    label: 'Civo Cloud',
    description: 'Simple cloud with GPU inference on Civo.',
    defaultBaseUrl: PROVIDER_DEFAULTS.civo.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  nimblebox: {
    id: 'nimblebox',
    label: 'NimbleBox.ai',
    description: 'Hosted inference and training on NimbleBox.',
    defaultBaseUrl: PROVIDER_DEFAULTS.nimblebox.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  gradient: {
    id: 'gradient',
    label: 'Gradient AI',
    description: 'Fine-tuned model endpoints on Gradient.',
    defaultBaseUrl: PROVIDER_DEFAULTS.gradient.baseUrl,
    requiresApiKey: true,
    staticModels: ['gradient-model'],
  },
  beam: {
    id: 'beam',
    label: 'Beam',
    description: 'Serverless GPU functions on Beam Cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.beam.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  mystic: {
    id: 'mystic',
    label: 'Mystic A.I.',
    description: 'Selective inference routing on Mystic.',
    defaultBaseUrl: PROVIDER_DEFAULTS.mystic.baseUrl,
    requiresApiKey: true,
    staticModels: ['mystic-model'],
  },
  fal: {
    id: 'fal',
    label: 'Fal.ai',
    description: 'Fast image, video and audio model endpoints.',
    defaultBaseUrl: PROVIDER_DEFAULTS.fal.baseUrl,
    requiresApiKey: true,
    staticModels: ['fal-model'],
  },
  replicateengine: {
    id: 'replicateengine',
    label: 'Replicate Engine',
    description: 'Dedicated engine deployments through Replicate.',
    defaultBaseUrl: PROVIDER_DEFAULTS.replicateengine.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta/meta-llama-3.1-405b-instruct'],
  },
  segmind: {
    id: 'segmind',
    label: 'Segmind',
    description: 'Hosted image and language model APIs on Segmind.',
    defaultBaseUrl: PROVIDER_DEFAULTS.segmind.baseUrl,
    requiresApiKey: true,
    staticModels: ['segmind-model'],
  },
  runhouse: {
    id: 'runhouse',
    label: 'Runhouse',
    description: 'Self-hosted compute served through Runhouse.',
    defaultBaseUrl: PROVIDER_DEFAULTS.runhouse.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  skypilot: {
    id: 'skypilot',
    label: 'SkyPilot',
    description: 'Managed clusters across clouds through SkyPilot.',
    defaultBaseUrl: PROVIDER_DEFAULTS.skypilot.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  foundry: {
    id: 'foundry',
    label: 'Foundry Cloud',
    description: 'Managed model endpoints on Foundry.',
    defaultBaseUrl: PROVIDER_DEFAULTS.foundry.baseUrl,
    requiresApiKey: true,
    staticModels: ['foundry-model'],
  },
  brev: {
    id: 'brev',
    label: 'Brev.dev',
    description: 'One-click GPU instances on Brev.',
    defaultBaseUrl: PROVIDER_DEFAULTS.brev.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  tensordock: {
    id: 'tensordock',
    label: 'TensorDock',
    description: 'Marketplace GPU cloud inference on TensorDock.',
    defaultBaseUrl: PROVIDER_DEFAULTS.tensordock.baseUrl,
    requiresApiKey: true,
    staticModels: ['meta-llama/Llama-3.3-70B-Instruct'],
  },
  oblivious: {
    id: 'oblivious',
    label: 'Oblivious AI',
    description: 'Privacy-preserved inference on Oblivious.',
    defaultBaseUrl: PROVIDER_DEFAULTS.oblivious.baseUrl,
    requiresApiKey: true,
    staticModels: ['oblivious-model'],
  },
  synthesia: {
    id: 'synthesia',
    label: 'Synthesia API',
    description: 'AI video avatars through the Synthesia API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.synthesia.baseUrl,
    requiresApiKey: true,
    staticModels: ['synthesia-model'],
  },
  elevenlabs: {
    id: 'elevenlabs',
    label: 'ElevenLabs API',
    description: 'Voice and speech models through the ElevenLabs API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.elevenlabs.baseUrl,
    requiresApiKey: true,
    staticModels: ['eleven-multilingual-v2', 'eleven-turbo-v2'],
  },
  openaimarketplace: {
    id: 'openaimarketplace',
    label: 'OpenAI Marketplace (Third-party hosts)',
    description: 'OpenAI-compatible third-party hosts of OpenAI models.',
    defaultBaseUrl: PROVIDER_DEFAULTS.openaimarketplace.baseUrl,
    requiresApiKey: true,
    staticModels: ['gpt-4o-mini'],
  },
  stability: {
    id: 'stability',
    label: 'Stability AI (Developer API)',
    description: 'Image generation models through the Stability API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.stability.baseUrl,
    requiresApiKey: true,
    staticModels: ['stable-image-core', 'stable-image-ultra'],
  },
  midjourney: {
    id: 'midjourney',
    label: 'Midjourney API (Unofficial)',
    description: 'Third-party proxies to Midjourney image generation.',
    defaultBaseUrl: PROVIDER_DEFAULTS.midjourney.baseUrl,
    requiresApiKey: true,
    staticModels: ['midjourney-model'],
  },
  leonardo: {
    id: 'leonardo',
    label: 'Leonardo.ai API',
    description: 'Image generation through the Leonardo.ai API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.leonardo.baseUrl,
    requiresApiKey: true,
    staticModels: ['leonardo-phoenix-1.0'],
  },
  runwayml: {
    id: 'runwayml',
    label: 'RunwayML Developer API',
    description: 'Video generation through the Runway developer API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.runwayml.baseUrl,
    requiresApiKey: true,
    staticModels: ['gen4_turbo', 'gen3a_turbo'],
  },
  pika: {
    id: 'pika',
    label: 'Pika Labs API',
    description: 'Video generation through the Pika Labs API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.pika.baseUrl,
    requiresApiKey: true,
    staticModels: ['pika-model'],
  },
  heygen: {
    id: 'heygen',
    label: 'HeyGen API',
    description: 'AI video avatars through the HeyGen API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.heygen.baseUrl,
    requiresApiKey: true,
    staticModels: ['heygen-model'],
  },
  tavus: {
    id: 'tavus',
    label: 'Tavus API',
    description: 'Conversational video interfaces through the Tavus API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.tavus.baseUrl,
    requiresApiKey: true,
    staticModels: ['tavus-model'],
  },
  hume: {
    id: 'hume',
    label: 'Hume AI',
    description: 'Empathic voice and expression models by Hume.',
    defaultBaseUrl: PROVIDER_DEFAULTS.hume.baseUrl,
    requiresApiKey: true,
    staticModels: ['hume-model'],
  },
  assemblyai: {
    id: 'assemblyai',
    label: 'AssemblyAI',
    description: 'Speech-to-text and audio intelligence through AssemblyAI.',
    defaultBaseUrl: PROVIDER_DEFAULTS.assemblyai.baseUrl,
    requiresApiKey: true,
    staticModels: ['assemblyai-model'],
  },
  deepgram: {
    id: 'deepgram',
    label: 'Deepgram',
    description: 'Speech-to-text and voice models through Deepgram.',
    defaultBaseUrl: PROVIDER_DEFAULTS.deepgram.baseUrl,
    requiresApiKey: true,
    staticModels: ['nova-2', 'nova-3'],
  },
  speechify: {
    id: 'speechify',
    label: 'Speechify API',
    description: 'Text-to-speech through the Speechify API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.speechify.baseUrl,
    requiresApiKey: true,
    staticModels: ['speechify-model'],
  },
  coqui: {
    id: 'coqui',
    label: 'Coqui AI',
    description: 'Open text-to-speech through the Coqui API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.coqui.baseUrl,
    requiresApiKey: true,
    staticModels: ['coqui-model'],
  },
  playht: {
    id: 'playht',
    label: 'Play.ht API',
    description: 'Text-to-speech voices through the Play.ht API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.playht.baseUrl,
    requiresApiKey: true,
    staticModels: ['playht-model'],
  },
  murf: {
    id: 'murf',
    label: 'Murf AI API',
    description: 'Studio text-to-speech through the Murf API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.murf.baseUrl,
    requiresApiKey: true,
    staticModels: ['murf-model'],
  },
  pinecone: {
    id: 'pinecone',
    label: 'Pinecone (Inference/Vector AI)',
    description: 'Managed vector search with hosted inference.',
    defaultBaseUrl: PROVIDER_DEFAULTS.pinecone.baseUrl,
    requiresApiKey: true,
    staticModels: ['pinecone-model'],
  },
  weaviate: {
    id: 'weaviate',
    label: 'Weaviate Cloud (Inference)',
    description: 'Vector database with hosted inference modules.',
    defaultBaseUrl: PROVIDER_DEFAULTS.weaviate.baseUrl,
    requiresApiKey: true,
    staticModels: ['weaviate-model'],
  },
  qdrant: {
    id: 'qdrant',
    label: 'Qdrant Cloud (Inference)',
    description: 'Vector search with hosted inference on Qdrant.',
    defaultBaseUrl: PROVIDER_DEFAULTS.qdrant.baseUrl,
    requiresApiKey: true,
    staticModels: ['qdrant-model'],
  },
  milvus: {
    id: 'milvus',
    label: 'Milvus / Zilliz Cloud',
    description: 'Managed Milvus vector search on Zilliz Cloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.milvus.baseUrl,
    requiresApiKey: true,
    staticModels: ['milvus-model'],
  },
  langchain: {
    id: 'langchain',
    label: 'LangChain / LangSmith',
    description: 'Pipelines and tracing through the LangChain platform.',
    defaultBaseUrl: PROVIDER_DEFAULTS.langchain.baseUrl,
    requiresApiKey: true,
    staticModels: ['langchain-model'],
  },
  llamaindex: {
    id: 'llamaindex',
    label: 'LlamaIndex Cloud',
    description: 'Managed indexes and agents through LlamaCloud.',
    defaultBaseUrl: PROVIDER_DEFAULTS.llamaindex.baseUrl,
    requiresApiKey: true,
    staticModels: ['llamaindex-model'],
  },
  voyage: {
    id: 'voyage',
    label: 'Voyage AI (Embedding Provider)',
    description: 'Embedding models tuned for retrieval quality.',
    defaultBaseUrl: PROVIDER_DEFAULTS.voyage.baseUrl,
    requiresApiKey: true,
    staticModels: ['voyage-3-large', 'voyage-3', 'voyage-3-lite'],
  },
  jina: {
    id: 'jina',
    label: 'Jina AI (Embedding/Rerank API)',
    description: 'Embeddings and reranking through the Jina API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.jina.baseUrl,
    requiresApiKey: true,
    staticModels: ['jina-embeddings-v3', 'jina-reranker-v2'],
  },
  mixedbread: {
    id: 'mixedbread',
    label: 'Mixedbread AI',
    description: 'Embeddings and reranking through the Mixedbread API.',
    defaultBaseUrl: PROVIDER_DEFAULTS.mixedbread.baseUrl,
    requiresApiKey: true,
    staticModels: ['mixedbread-embed-large-v1'],
  },
  nomic: {
    id: 'nomic',
    label: 'Nomic AI',
    description: 'Open embedding and atlas models by Nomic.',
    defaultBaseUrl: PROVIDER_DEFAULTS.nomic.baseUrl,
    requiresApiKey: true,
    staticModels: ['nomic-embed-text-v1.5'],
  },
  coherererank: {
    id: 'coherererank',
    label: 'Cohere Rerank API',
    description: 'Reranking through the Cohere v2 endpoint.',
    defaultBaseUrl: PROVIDER_DEFAULTS.coherererank.baseUrl,
    requiresApiKey: true,
    staticModels: ['rerank-v3.5'],
  },
  telnyx: {
    id: 'telnyx',
    label: 'Telnyx AI',
    description: 'Inference and voice AI on the Telnyx network.',
    defaultBaseUrl: PROVIDER_DEFAULTS.telnyx.baseUrl,
    requiresApiKey: true,
    staticModels: ['telnyx-model'],
  },
};

export const PROVIDER_LABELS: Record<ProviderId, string> = Object.fromEntries(
  PROVIDER_IDS.map((id) => [id, PROVIDER_DEFINITIONS[id].label]),
) as Record<ProviderId, string>;

export function isProviderId(value: unknown): value is ProviderId {
  return typeof value === 'string' && PROVIDER_IDS.includes(value as ProviderId);
}

export function isLanguage(value: unknown): value is Language {
  return value === 'en' || value === 'ja' || value === 'zh';
}

export function normalizeBaseUrl(value: string): string {
  return value.trim().replace(/\/+$/, '');
}

export function providerFor(provider: ProviderId): ProviderDefinition {
  return isProviderId(provider) ? PROVIDER_DEFINITIONS[provider] : PROVIDER_DEFINITIONS.openai;
}
